sudo: required
services: 
  - docker 

before_install:
   - docker build -t illtemperedklavier/docker-react -f Dockerfile.dev . 

language: generic 

script:
   - docker run -e CI=true illtemperedklavier/docker-react npm run test

deploy:
   provider: elasticbeanstalk 
   region: "us-east-2"
   app: "docker-react"
   env: "docker-react-env"
   bucket_name: "elasticbeanstalk-us-east-2-202794998449"
   bucket_path: "docker-react"
   on:
      branch: master 